# Generated by Django 5.1.3 on 2024-11-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_profile_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
