# Generated by Django 5.1.3 on 2024-11-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='room_image/'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_type_image', to='rooms.roomtype'),
        ),
    ]
