# Generated by Django 5.1.3 on 2024-12-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_quest',
            new_name='total_guest',
        ),
    ]
