# Generated by Django 5.1.3 on 2024-11-26 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomimage_image_alter_roomimage_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='per_day_charges',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('payment_status', models.CharField(default='pending', max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_invoice', to='rooms.booking')),
            ],
        ),
    ]
